#!/usr/bin/env bash
energy=$(cat /sys/class/power_supply/BAT0/energy_now)
full=$(cat /sys/class/power_supply/BAT0/energy_full_design)
is_charging=$(cat /sys/class/power_supply/BAT0/status)

if [ $is_charging = "Charging" ]; then
	is_charging=true
else
	is_charging=false
fi

charge=$((bc <<< "scale=4; ($energy/$full)*100") | sed -E 's/([0-9]+\.[0-9]{2})[0-9]*/\1/')

echo "{\"charge\":\"$charge\",\"status\":\"$is_charging\"}"
