#!/usr/bin/env bash
function print_stuff {
	vol=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Eo --color=never "[0-9]*%" | head -1)
	vol=${vol::-1}
	is_mute=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -Eo "yes|no") 
	if [ "$is_mute" = "yes" ]; then
		is_mute=true
	else
		is_mute=false
	fi

	echo "{\"is_mute\":$is_mute,\"vol\":$vol}"
}

print_stuff
pactl subscribe | grep --line-buffered "change" | while read EVENT; do
	print_stuff
done
