#!/usr/bin/env bash
~/.config/eww/scripts/format_workspaces $(swaymsg -r -t get_workspaces | jq -c '[.[] | {num, focused}]')
swaymsg -m -t subscribe '["workspace"]' | grep --line-buffered "\"change\"" | while read EVENT; do
	~/.config/eww/scripts/format_workspaces $(swaymsg -r -t get_workspaces | jq -c '[.[] | {num, focused}]')
done
